version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: backend/BookRecommenderApi/Dockerfile
      args:
        PROJECT_PATH: backend/BookRecommenderApi
    ports:
      - "8080:8080"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - db

  ui:
    build:
      context: ./book-recommender-ui
    ports:
      - "4200:80"
    depends_on:
      - api

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bookrecommender-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin      

volumes:
  pgdata:
  pgadmin_data: