name: BookRecommender UI CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'BookRecommender/book-recommender-ui/**'
      - '.github/workflows/bookrecommender-ui.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: BookRecommender/book-recommender-ui
        run: npm ci

      - name: Build Angular
        working-directory: BookRecommender/book-recommender-ui
        run: npm run build -- --configuration=production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "BookRecommender/book-recommender-ui"
          # NOTE: the dist subfolder name must match your Angular project name in angular.json.
          # The project is named "book-recommender-ui", so the output goes to dist/book-recommender-ui:
          output_location: "dist/book-recommender-ui"
