name: BookRecommender Proto - Build UI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'BookRecommender_proto/ui/**'
      - '.github/workflows/bookrecommender-proto-ui-build.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'BookRecommender_proto/ui/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test Angular App
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'BookRecommender_proto/ui/package-lock.json'

    - name: Install dependencies
      working-directory: ./BookRecommender_proto/ui
      run: npm ci

    - name: Run linting
      working-directory: ./BookRecommender_proto/ui
      run: npm run lint --if-present

    - name: Run tests
      working-directory: ./BookRecommender_proto/ui
      run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

    - name: Upload test coverage
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: BookRecommender_proto/ui/coverage/
        retention-days: 7

    - name: Build application for production
      working-directory: ./BookRecommender_proto/ui
      run: npm run build -- --configuration=production

    - name: Upload build artifacts
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: BookRecommender_proto/ui/dist/
        retention-days: 30

    - name: Run build size analysis
      if: matrix.node-version == '20.x'
      working-directory: ./BookRecommender_proto/ui
      run: |
        echo "## Bundle Analysis" >> $GITHUB_STEP_SUMMARY
        echo "Built successfully! Bundle size information:" >> $GITHUB_STEP_SUMMARY
        ls -la dist/ui/browser/ >> $GITHUB_STEP_SUMMARY
