name: BookRecommender API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'BookRecommender/backend/**'
      - '.github/workflows/bookrecommender-api.yml'
  workflow_dispatch:

env:
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  RG: ${{ secrets.AZURE_RG }}
  WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  IMAGE_NAME: bookrecommenderapi
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # Set context to the app’s top folder so subsequent paths can be short
  CONTEXT: BookRecommender
  DOCKERFILE: BookRecommender/backend/BookRecommenderApi/Dockerfile
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Step 1 — Decode AZURE_CREDENTIALS_B64 to creds.json
      - name: Decode Azure credentials
        run: echo "${{ secrets.AZURE_CREDENTIALS_B64 }}" | base64 --decode > $HOME/creds.json

      # Step 2 — Read creds.json into an output variable
      - name: Decode Azure credentials
        id: read_creds
        run: |
          echo 'json<<EOF' >> "$GITHUB_OUTPUT"
          echo "${{ secrets.AZURE_CREDENTIALS_B64 }}" | base64 --decode >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      - name: Debug AZURE_CREDENTIALS
        run: |
          echo "${{ steps.read_creds.outputs.json }}"

      # Step 3 — Login to Azure using the decoded JSON
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ steps.read_creds.outputs.json }}      

      - name: Debug ACR name
        id: acr_dbg
        shell: bash
        run: |
          set -euo pipefail
          RAW="${{ env.ACR_NAME }}"
          echo "RAW env.ACR_NAME -> '${RAW}'"

          # Normalize (handles 'myregistry.azurecr.io' or accidental URL paste)
          NAME="$RAW"
          NAME="${NAME#https://}"
          NAME="${NAME#http://}"
          NAME="${NAME%%.azurecr.io}"
          NAME="$(echo "$NAME" | tr '[:upper:]' '[:lower:]')"

          echo "Normalized -> '${NAME}'"
          echo "Length -> ${#NAME}"
          printf "ASCII codes -> "; echo -n "$NAME" | od -An -t u1

          # Validate format: 5–50 lowercase letters/digits only
          if [[ ! "$NAME" =~ ^[a-z0-9]{5,50}$ ]]; then
            echo "::error::ACR name invalid. It must be the short name (e.g. 'myregistry'), NOT 'myregistry.azurecr.io'."
            exit 1
          fi

          echo "name=$NAME" >> "$GITHUB_OUTPUT"
          echo "loginServer=${NAME}.azurecr.io" >> "$GITHUB_OUTPUT"

      - name: Try ACR show (permission check)
        shell: bash
        run: |
          set -e
          az acr show -n "${{ steps.acr_dbg.outputs.name }}" -o table || {
            echo "::error::'az acr show' failed. This usually means the service principal lacks access (needs AcrPush/Contributor on the ACR or its RG)."
            exit 1
          }

      - name: ACR login
        run: az acr login --name ${{ steps.acr_dbg.outputs.name }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ steps.acr_dbg.outputs.loginServer }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            PROJECT_PATH=backend/BookRecommenderApi

      # Grant AcrPull to the Web App MI (idempotent)
      - name: Grant AcrPull to Web App MI if not present
        run: |
          set -e
          SUB_ID="$(az account show --query id -o tsv)"
          PID="${{ secrets.AZURE_WEBAPP_MI_PRINCIPAL_ID }}"
          ACR="${{ steps.acr_dbg.outputs.name }}"
          SCOPE="/subscriptions/$SUB_ID/resourceGroups/$RG/providers/Microsoft.ContainerRegistry/registries/$ACR"

          if az role assignment list --assignee "$PID" --scope "$SCOPE" --query "[?roleDefinitionName=='AcrPull']" -o tsv | grep -q .; then
            echo "AcrPull already assigned to $PID on $SCOPE"
          else
            echo "Assigning AcrPull to $PID on $SCOPE"
            az role assignment create --assignee "$PID" --role AcrPull --scope "$SCOPE" >/dev/null
          fi

      # Configure Web App to use MI for ACR pulls (no pre-read)
      - name: Configure Web App for MI-based ACR pull
        run: |
          set -e
          az webapp config container set -g "$RG" -n "$WEBAPP_NAME" \
            --docker-custom-image-name "${{ steps.acr_dbg.outputs.loginServer }}/${IMAGE_NAME}:${TAG}" \
            --docker-registry-server-url "https://${{ steps.acr_dbg.outputs.loginServer }}"
          az webapp config set -g "$RG" -n "$WEBAPP_NAME" --acr-use-managed-identity true
          az webapp config appsettings set -g "$RG" -n "$WEBAPP_NAME" --settings WEBSITES_PORT=8080

      - name: (Optional) Set OpenAI key as app setting
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          az webapp config appsettings set -g $RG -n $WEBAPP_NAME --settings OpenAI__ApiKey=${{ secrets.OPENAI_API_KEY }}

      - name: Restart Web App
        run: az webapp restart -g $RG -n $WEBAPP_NAME
